### ISSUE TITLE
t-SNE plots for internal layers

### ISSUE THREAD

**Issue by vinitveersingh** [AlonLahav/MeshWalker#11]
Hi Alon,
Hope you are well. Would it be possible for you to share the code used to visualize the t-SNE for the input and internal layers? I am referring to Fig. 8 of your paper?

Thanks,
Vinit

**Comment by AlonLahav** [comment]
Hi,
I don't have a "clean" code for this, but I will try to make one.
It will probably take a while to to so..
Alon.

**Comment by vinitveersingh** [comment]
Okay thank you
