### ISSUE TITLE
CUBES Train/Test Split

### ISSUE THREAD

**Issue by vinitveersingh** [AlonLahav/MeshWalker#12]
Hi Alon,
I hope you are well. I downloaded the CUBES data set from the provided link and noticed the train/test split is different from the one mentioned in the original paper.
This is the line from your paper: 
"This dataset contains 4600 objects, with 3910/690
training/testing split. Each object is a cube "engraved" with a shape
at a random face in a random location, as demonstrated in Fig. 4.
The engraved shape belongs to a dataset of 23 classes (e.g., car,
heart, apple, etc.), each contains roughly 20 shapes. "
However, the downloaded link provides a train/test split of 3722/659 with 22 classes. And the total meshes add up to 4381 instead of 4600.
I noticed the authors of MeshCNN had modified their dataset, and I have raised the same issue there, but  I haven't received a reply from them.
https://github.com/ranahanocka/MeshCNN/issues/120

I would really appreciate some clarification on this.

**Comment by AlonLahav** [comment]
Hi, I am sorry for the delay.
I don't remember the exact number of examples, but I think there is no signeficant difference.
It might be a misstake in the paper or misstake in the dataset I've uploaded.
