### ISSUE TITLE
Error in Segmentation Evaluation

### ISSUE THREAD

**Issue by kumarabhinav04** [AlonLahav/MeshWalker#13]
Hi,

When I am trying to execute the segmentation code (evaluate_segmentation) on ModelNet40 dataset, I get the following error

![image](https://user-images.githubusercontent.com/5492783/116051510-4ea9fb00-a696-11eb-84d8-13583df9d479.png)

This is my script to execute the segmentation on pre-trained model
python evaluate_segmentation.py modelnet40 --- pretrained/0497-20.05.2020..21.17__modelnet__SeqLen800

Kindly help

**Comment by AlonLahav** [comment]
Hi,
ModelNet40 is for classification only. Segmentation works on other datasets.

Hope it helps,
Alon.

**Comment by JacobCummins** [comment]
Just to add to this slightly, the original poster might have gotten confused because the README.md is wrong and ideally would be updated.

![Image](https://github.com/user-attachments/assets/b00d7f02-0d0d-4918-8793-57b35bd618cf)
