### ISSUE TITLE
Question: The number of walks in evaluation

### ISSUE THREAD

**Issue by xdhdx** [AlonLahav/MeshWalker#16]
Hi, the paper mentioned that the **walk number in classification task is 32**, **for segmentation task it's 32 * #SegClsNum**.  

But as I read the code, I don't know if I am misunderstanding the code, I found that for shrec, cubes, the default value is 16, see [code](https://github.com/AlonLahav/MeshWalker/blob/f3b73b1e165ec6598dc10826245df8d9b6c4d8eb/evaluate_classification.py#L32). For modelnet40, the number is 64, see [code](https://github.com/AlonLahav/MeshWalker/blob/f3b73b1e165ec6598dc10826245df8d9b6c4d8eb/params_setting.py#L99)

For the segmentation task, the walk number is 32 * 32 see [code](https://github.com/AlonLahav/MeshWalker/blob/f3b73b1e165ec6598dc10826245df8d9b6c4d8eb/evaluate_segmentation.py#L163).  

I wonder to know the number of walks for the results in the paper. Any help regarding this is appreciated! Thanks in advance.

Best wishes.

**Comment by AlonLahav** [comment]
Hi, I am sorry for the delay.
I think that there will be no significant difference in the results anyway.
Not sure if the mismatch is due to older code or the parameter in the paper are not accurate.
