### ISSUE TITLE
error with : "tensorboard <trained-model-folder>" 

### ISSUE THREAD

**Issue by ToToVa06** [AlonLahav/MeshWalker#18]
Hello, I contact you because of a problem when using the command with "tensorboard".
Indeed, after having installed all the necessary packages (in the right version), it is impossible for me to execute this command  `tensorboard <trained-model-folder>`.
 In my case, I use:

![image](https://user-images.githubusercontent.com/82272458/167650688-f4a0149d-3a2d-4328-8855-26e9bf850786.png)

(the "0003-10.05.2022..13.58__cubes " folder is obtained after executing the command : `python train_val.py cubes`)

Because there is no tensorboard.main file and I get the following errors :
![error1](https://user-images.githubusercontent.com/82272458/167655403-5ea68913-8ec0-46d1-9258-00f642c94690.PNG)
![error2](https://user-images.githubusercontent.com/82272458/167655430-42dd3775-1bc7-478a-b3b3-276647c719e3.PNG)
![image](https://user-images.githubusercontent.com/82272458/167647641-7f54d552-e13b-4192-818b-34feb07e4fbf.png)

(I use windows 10)
Do you know how I could proceed to solve this problem ?

**Comment by AlonLahav** [comment]
Hi,
I have no idea what can couse this issue.
Since this is not related to the code you run, I do suggest to install all packages, and look for tensorflow documentation to find the solution.
Best,
Alon.
