### ISSUE TITLE
What is the model_ftrs_ in test_dataset?

### ISSUE THREAD

**Issue by supil9545** [AlonLahav/MeshWalker#5]
what means the moel_ftrs_ in the test_dataset?
And I want to know how to create model_ftrs_ in ply or obj files

**Comment by AlonLahav** [comment]
In most of this code, `model_ftrs` means the input to the RNN network.
Please specify file name and line number, so my answer will be more specific..

To create the input to the network from a mesh, it is more complicated:
1 - You sould generate a `dataset` using `dataset_prepare.py`
2 - The `model_ftrs` will be composed in `dataset.py` as part of the training or evaluating run

Hope this helps..
Alon.
