### ISSUE TITLE
Unable to reproduce results on SHREC11

### ISSUE THREAD

**Issue by vinitveersingh** [AlonLahav/MeshWalker#6]
Hello,
Hope you are well. I downloaded the code and your preprocessed data and ran the code as mentioned on the shrec data:
python train_val.py shrec11 16-04_A
However, after 4002 epochs the maximum test accuracy I am able to obtain is 0.82%:
26932) Epoch3985, iter 59760, TrnLoss: 2.15, test/accuracy_shrec16: 0.82, time: 4.5

Similarly, when I train:
python train_val.py shrec11 16-04_B,
the maximum test accuracy I achieve is 0.84%.
30624) Epoch3986, iter 59775, TrnLoss: 2.17, test/accuracy_shrec16: 0.84, time: 4.7

Your paper reported 98% accuracy on the three parts on average. 
I am not sure why this could be happening and would appreciate your help.

Thank you.

**Comment by AlonLahav** [comment]
Hi,

I think I know the reason you get low accuracy - please refer to my note (at the README):
```
Note that "accuracy" tab is a fast accuracy calculated while training, it is not the final accuracy we get using averaging. 
To get the final accuracy results, please refer to the "full_accuracy" tab at tensorboard, or run evaluation scripts.
```
Please let me know if it solves your issue..

Alon.

**Comment by vinitveersingh** [comment]
Thank you, Alon. It solves the issue.
