### ISSUE TITLE
Number of training epochs

### ISSUE THREAD

**Issue by vinitveersingh** [AlonLahav/MeshWalker#7]
Hello,
I had a question about the number of epochs, compared to other methods (like MeshCNN) your method runs for far more epochs. Like in the case of ModelNet40, 500000 iterations. Is this due to a typo or does MeshWalker need to be trained so much? 

Thanks again.

**Comment by AlonLahav** [comment]
Hi,

I'm glad to have this discussion with you, hope it helps you..

Regarding your question, don't forget MeshWalker is **very** different from other methods.
Number of iteration is not a typo - it does take many iterations compared to MeshCNN which is super-fast :)

Alon.

**Comment by vinitveersingh** [comment]
Hi Alon, thank you for confirming :)
