### ISSUE TITLE
the raw data of shrec11

### ISSUE THREAD

**Issue by zj-123456** [AlonLahav/MeshWalker#9]
Hello,
Hope you are well. Would you please send me a copy of the raw data of shrec11, 20187196@stu.nmu.edu.cn,thank you very much!

**Comment by AlonLahav** [comment]
Hi,
You are right - I haven't uploaded it..
I will try to do so, but not sure I still have it..
Meanwhile you can use the preprocessed one (from `https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Software/MeshWalker/mesh_walker_data/datasets_processed/`)

**Comment by zj-123456** [comment]
Thank you. I have downloaded it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlonLahav/MeshWalker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlonLahav/MeshWalker] the raw data of shrec11 (#9)





 
Hi,
 You are right - I haven't uploaded it..
 I will try to do so, but not sure I still have it..
 Meanwhile you can use the preprocessed one (from https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Software/MeshWalker/mesh_walker_data/datasets_processed/)

**Comment by zj-123456** [comment]
Hi,
Sorry, the last email didn't make it clear. Thank you, I have downloaded your data set from your website, but I need the raw data. If you can find it, please send me one.&nbsp;
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlonLahav/MeshWalker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlonLahav/MeshWalker] the raw data of shrec11 (#9)





 
Hi,
 You are right - I haven't uploaded it..
 I will try to do so, but not sure I still have it..
 Meanwhile you can use the preprocessed one (from https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Software/MeshWalker/mesh_walker_data/datasets_processed/)
